# -*- coding: utf-8 -*-
"""Aplanarlistaanidada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qkmsMXM_MaUPQEFhoHCkUudxXx2zPTNw
"""

def aplanar(x):
    if not x:
        return []
    cabeza, resto = x[0], x[1:]
    if isinstance(cabeza, int):
        return [cabeza] + aplanar(resto)
    return aplanar(cabeza) + aplanar(resto)

# Pruebas
print(aplanar([]))                       # []
print(aplanar([1,2,3]))
print(aplanar([1,[2,[3,4],5],[],6]))