# -*- coding: utf-8 -*-
"""Factorial (Básico) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwlPk0XWxTmCLfISUHBgngpaFQc7IQDQ
"""

def factorial(n: int) -> int:
#Calcula n! recursivamente.
#Precondición: n >= 0
  if n < 0:
    raise ValueError ("factorial: n debe ser >= 0")
  if n == 0 or n == 1:
    return 1
  return n * factorial(n - 1)
  print(factorial(-1))
print(factorial(1))
print(factorial(5))