# -*- coding: utf-8 -*-
"""Fibonacci (Básico–Intermedio) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J05qebGmCynY_TUG0cAPfYChRIpR8buP
"""

from typing import Dict

def fibo(n: int) -> int:
    if n < 0:
        raise ValueError("fibo: n debe ser >= 0")
    if n == 0:
        return 0
    if n == 1:
        return 1
    return fibo(n - 1) + fibo(n - 2)

def fibo_memo(n: int, memo: Dict[int, int] | None = None) -> int:
    if n < 0:
        raise ValueError("fibo_memo: n debe ser >= 0")
    if memo is None:
        memo = {0: 0, 1: 1}
    if n in memo:
        return memo[n]
    memo[n] = fibo_memo(n - 1, memo) + fibo_memo(n - 2, memo)
    return memo[n]

# Pruebas
print(fibo(10))
print(fibo_memo(10))