# -*- coding: utf-8 -*-
"""Maximo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11EJ-LgcxDmqMkztHwvMAvAAHs_MSp0Qy
"""

def maximo(lst):
    """
    Devuelve el máximo de una lista no vacía recursivamente.
    Precondición: len(lst) >= 1
    """
    if not lst:
        raise ValueError("maximo: la lista no debe estar vacía")
    if len(lst) == 1:
        return lst[0]
    max_resto = maximo(lst[1:])
    return lst[0] if lst[0] >= max_resto else max_resto

# Pruebas
print(maximo([3, 5, 2, 9, 1]))
print(maximo([7]))